name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: ImdataScientistSachin/Ratina_Face
          huggingface_repo_id: ImdataScientistSachin/Ratina_Face
          repo_type: space
          hf_token: ${{ secrets.HF_TOKEN }}
